def raise_exception():
    raise ValueError("An error occurred!")

def main():
    raise_exception() 

main()
